<?php

/**
 * Colombia places
 *
 * @author   Saul Morales Pacheco <moralespachecopablo@gmail.com>
 * @version  1.1.33
 * @license http=>//opensource.org/licenses/gpl-license.php GNU Public License
 */
global $places;

$places['EC'] = array(

    'EC-P' => array(
        "TABACUNDO",
        "CAYAMBE",
        "PEDRO MONCAYO",
        "AYORA",
        "JUAN MONTALVO",
        "QUITO",
        "ALANGASI",
        "ALOAG",
        "AMAGUAÑA",
        "CONOCOTO",
        "CUMBAYA",
        "GUAYLLABAMBA",
        "LA ARMENIA",
        "LLANO CHICO",
        "LLANO GRANDE",
        "MACHACHI",
        "MIRAVALLE",
        "MITAD DEL MUNDO",
        "MONJAS",
        "ORQUIDEAS",
        "PIFO",
        "PINTAG",
        "POMASQUI",
        "PUEMBO",
        "PUSUQUI",
        "EL QUINCHE",
        "AZCASUBI VIA AL QUINCHE",
        "CHECA",
        "SAN ANTONIO DE PICHINCHA",
        "SAN JOSE DE MORAN",
        "CALDERON",
        "SAN RAFAEL",
        "SANGOLQUI",
        "TABABELA",
        "TAMBILLO",
        "TUMBACO",
        "UYUMBICHO",
        "VALLE DE LOS CHILLOS",
        "YARUQUI",
        "ZAMBISA",
        "PUERTO QUITO",
        "PEDRO V. MALDONADO",
        "SAN MIGUEL DE LOS BANCOS",
        "NANEGALITO",
        "CALACALI",
        "CUZUBAMBA",
    ),

    'EC-X' => array(
        "LATACUNGA",
        "SALCEDO",
        "SAQUISILI",
        "LASSO",
        "GUAYTACAMA",
        "PASTOCALLE",
        "MULALO",
        "TANICUCHI",
        "BELISARIO QUEVEDO",
        "PUJILI",
        "SAN BUENAVENTURA -BELLAVISTA.",
        "LA MANA",
    ),

    'EC-C' => array(
        "TULCAN",
        "SAN GABRIEL",
        "EL ANGEL",
        "JULIO ANDRADE",
        "BOLIVAR",
        "HUACA",
        "MIRA",
    ),

    'EC-I' => array(
        "IBARRA",
        "CARANQUI",
        "URCUQUI",
        "YAGUARCOCHA",
        "ATUNTAQUI",
        "ANDRADE MARIN",
        "CHALTURA",
        "SAN LUIS",
        "SANTA BERTHA",
        "TIERRA BLANCA",
        "SAN JOSE",
        "NATABUELA",
        "ANTONIO ANTE",
        "PIMAMPIRO",
        "SAN ANTONIO IBARRA",
        "SAN ROQUE",
        "CHORLAVI",
        "OTAVALO",
        "COTACACHI",
        "SAN PABLO IMBABURA",
        "QUIROGA",
        "GONZALEZ SUAREZ",
        "PERUGACHI",
        "PEGUCHE",
    ),

    'EC-B' => array(
        "GUARANDA",
        "SALINAS DE GUARANDA",
        "SAN JOSE DE CHIMBO ",
        "SAN MIGUEL DE BOLIVAR",
    ),

    'EC-A' => array(
        "CUENCA",
        "CHAULLABAMBA",
        "RICAURTE CUENCA",
        "GUALACEO",
        "SIG SIG",
        "PAUTE",
        "CHORDELEG",
        "ZONA FRANCA",
        "CUMBE",
        "TARQUI",
        "GIRON",
        "YUNGUILLA",
        "SANTA ISABEL",
        "OÑA",
        "PONCE ENRIQUEZ",
    ),

    'EC-F' => array("AZOGUES", "BIBLIAN", "CAÑAR", "EL TAMBO"),

    'EC-H' => array(
        "RIOBAMBA",
        "GUANO",
        "CAJABAMBA",
        "CHUNCHI",
        "LICAN",
        "ALAUSI",
        "GUAMOTE",
        "COLTA",
        "CHAMBO",
        "YARUQUIES",
    ),

    "EC-O" => array(
        "MACHALA",
        "PIÑAS",
        "ZARUMA",
        "PORTOVELO",
        "PUERTO BOLIVAR",
        "ARENILLAS",
        "PASAJE",
        "SANTA ROSA",
        "SANTA ROSA",
        "HUAQUILLAS",
        "EL CAMBIO",
        "EL GUABO",
    ),

    'EC-E' => array(
        "ESMERALDAS",
        "ATACAMES",
        "TONSUPA",
        "TACHINA",
        "LA UNION",
        "QUININDE",
        "VICHE",
    ),

    'EC-G' => array(
        "JUJAN",
        "TRES POSTES",
        "GUAYAQUIL",
        "DURAN",
        "DAULE",
        "SAMBORONDON (Pueblo)",
        "BOCA DE CAÑA",
        "NOBOL",
        "ISIDRO AYORA",
        "LOMAS DE SARGENTILLO",
        "PEDRO CARBO",
        "ISIDRO AYORA",
        "PALESTINA",
        "SANTA LUCIA",
        "BALZAR",
        "LAUREL",
        "SALITRE",
        "SAMBORONDON",
        "CHIVERIA",
        "PETRILLO",
        "PUENTE LUCIA",
        "COLORADAL",
        "GENERAL VERNAZA",
        "LA MARAVILLA",
        "LAS ANIMAS",
        "LOS TINTOS",
        "SABANILLA",
        "TARIFA",
        "PLAYAS",
        "CERECITA",
        "CHONGON",
        "POSORJA",
        "PROGRESO",
        "MILAGRO",
        "BASE TAURA",
        "EL DESEO",
        "MATILDE ESTHER",
        "KM 26 VIA DURAN TAMBO",
        "BUCAY",
        "BOLICHE",
        "CUMANDA",
        "ROBERTO ASTUDILLO",
        "YAGUACHI",
        "NARANJITO",
        "EL TRIUNFO",
        "LA TRONCAL",
        "MARCELINO MARIDUEÑA",
        "MANUEL J. CALLE",
        "SIMON BOLIVAR",
        "MARISCAL SUCRE",
        "LORENZO DE GARAICOA",
        "NARANJAL",
        "BALAO",
        "BALAO",
        "PUERTO INCA",
    ),

    'EC-L' => array(
        "LOJA",
        "Vilcabamba",
        "Cariamanga",
        "Catacocha",
        "Catamayo",
        "Celica",
        "Saraguro",
        "Malacatos",
        "Gonzanama",
        "Macara",
    ),

    "EC-R" => array(
        "VALENCIA",
        "MOCACHE",
        "QUINSALOMA",
        "SAN CARLOS",
        "PATRICIA PILAR",
        "BABAHOYO",
        "VINCES",
        "PALENQUE",
        "ISLA BEJUCAL",
        "BABA",
        "ECHEANDIA",
        "MONTALVO",
        "CALUMA",
        "PUEBLO VIEJO",
        "CATARAMA",
        "RICAURTE LOS RIOS",
        "SAN JUAN",
        "VENTANAS",
        "QUEVEDO",
        "SAN CAMILO",
        "BUENA FE",
        "EL EMPALME",
    ),

    'EC-M' => array(
        "PEDERNALES",
        "EL CARMEN",
        "NUEVO ISRAEL",
        "LA DELICIA KM. 29",
        "CHONE",
        "CALCETA",
        "CANUTO",
        "ESTANCILLA",
        "FLAVIO ALFARO",
        "RICAURTE MANABI",
        "SAN ANTONIO DE CHONE",
        "JUNIN",
        "TOSAGUA",
        "BAHIA DE CARAQUEZ",
        "LEONIDAS PLAZA",
        "SAN VICENTE",
        "JAMA",
        "MANTA",
        "MONTECRISTI",
        "JARAMIJO",
        "PORTOVIEJO",
        "ALAHUELA",
        "CALDERON DE PORTOVIEJO",
        "CHARAPOTO",
        "CRUCITA",
        "PICOAZA (DENTRO DEL PERIMETRO URBANO)",
        "SAN PLACIDO (DENTRO DEL PERIMETRO URBANO)",
        "RIO CHICO (DENTRO DEL PERIMETRO URBANO)",
        "ROCAFUERTE",
        "24 DE MAYO",
        "OLMEDO",
        "SANTA ANA",
        "COLON",
        "JIPIJAPA",
        "PUERTO CAYO",
        "PUERTO LOPEZ",
        "PAJAN",
        "PICHINCHA MANABI",
    ),

    "EC-S" => array("MACAS", "SUCUA", "GUALAQUIZA"),

    'EC-N' => array(
        "EL CHACO",
        "ARCHIDONA",
        "TENA",
        "MISAHUALLI",
        "PTO. NAPO",
        "AROSEMENA TOLA",
    ),

    'EC-D' => array(
        "(FRANCISCO DE ORELLANA) EL COCA",
        "LA JOYA DE LOS SACHAS",
        "LORETO",
    ),

    'EC-Y' => array("PUYO", "SHELL"),

    "EC-SE" => array(
        "LA LIBERTAD",
        "SANTA ELENA",
        "BALLENITA",
        "SALINAS",
        "MUEY",
        "PUERTO SANTA ROSA",
        "ANCON",
        "ANCONCITO",
        "MAR BRAVO",
        "PUNTA CARNERO",
        "PROSPERIDAD",
        "MANGLARALTO",
        "MONTAÑITA",
        "OLON",
        "SAN PABLO SANTA ELENA",
        "PUNTA BLANCA",
        "CADEATE",
        "CAPAES",
        "LIBERTADOR BOLIVAR",
        "MONTEVERDE",
        "PALMAR",
        "PUNTA BARANDUA",
        "SAN PEDRO",
        "VALDIVIA",
        "AYANGUE",
    ),

    "EC-SD" => array(
        "SANTO DOMINGO",
        "KM 14 QUEVEDO",
        "KM 24 QUEVEDO",
        "KM 38.5 QUEVEDO",
        "KM 41 QUEVEDO",
        "LUZ DE AMERICA",
        "LA CONCORDIA",
        "LAS VILLEGAS",
        "MONTERREY",
        "VALLE HERMOSO",
    ),

    'EC-U' => array("NUEVA LOJA - LAGO AGRIO", "SHUSHUFINDI"),

    'EC-T' => array(
        "AMBATO",
        "MOCHA",
        "CEVALLOS",
        "QUERO",
        "BAÑOS DE AGUA SANTA",
        "PELILEO",
        "PATATE",
        "TISALEO",
        "HUAMBALO",
        "PILLARO",
    ),

    "EC-Z" => array("ZAMORA", "YANTZAZA", "CENTINELA DEL CONDOR"),

);
