<?php

/**
 * Colombia places
 *
 * @author   Saul Morales Pacheco <moralespachecopablo@gmail.com>
 * @version  1.1.33
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 */
global $places;

$places['PA'] = [

    'PA-9' => [ //Veraguas
        'ARENAS',
        'ATALAYA',
        'BAHIA HONDA',
        'BARNIZAL',
        'BISVALLES',
        'BORO',
        'CALIDONIA',
        'CALOBRE',
        'CALOVEBORA',
        'CANAZAS',
        'CANTO DEL LLANO',
        'CARLOS SANTANA AVILA',
        'CATIVE',
        'CATORCE DE NOVIEMBRE',
        'CEBACO',
        'CERRO DE CASA',
        'CERRO DE PLATA',
        'CHITRA',
        'COROZAL',
        'CORRAL FALSO',
        'COSTA HERMOSA',
        'EDWIN FABREGA',
        'EL ALTO',
        'EL AROMILLO',
        'EL BARRITO',
        'EL CACAO',
        'EL COCLA',
        'EL CUAY',
        'EL MARANON',
        'EL MARIA',
        'EL PANTANO',
        'EL PICADOR',
        'EL POTRERO',
        'EL PRADO',
        'EL RINCON',
        'GATUNCITO',
        'GOBERNADORA',
        'GUARUMAL',
        'LA CARRILLO',
        'LA COLORADA',
        'LA GARCEANA',
        'LA LAGUNA',
        'LA MESA',
        'LA MONTANUELA',
        'LA PENA',
        'LA RAYA DE CALOBRE',
        'LA RAYA DE SANTA MARIA',
        'LA SOLEDAD',
        'LA TETILLA',
        'LA YEGUADA',
        'LAS CRUCES',
        'LAS GUIAS',
        'LAS HUACAS',
        'LAS PALMAS',
        'LAS PALMAS VERAGUAS',
        'LEONES',
        'LLANO DE CATIVAL O MARIAT',
        'LLANO GRANDE',
        'LOS ALGARROBOS',
        'LOS CASTILLOS',
        'LOS HATILLOS',
        'LOS MILAGROS',
        'LOS VALLES',
        'MONJARAS',
        'MONTIJO',
        'OLA',
        'PILON',
        'PIXVAE',
        'PONUGA',
        'PUERTO VIDAL',
        'QUEBRADA DE ORO',
        'QUEBRO',
        'REMANCE',
        'RIO DE JESUS',
        'RIO GRANDE',
        'RIO LUIS',
        'RODEO VIEJO',
        'RUBEN CANTU',
        'SAN ANTONIO',
        'SAN BARTOLO',
        'SAN FRANCISCO',
        'SAN JOSE',
        'SAN JUAN',
        'SAN MARCELO',
        'SAN MARTIN DE PORRES',
        'SAN PEDRO DEL ESPINO',
        'SANTAFE',
        'SANTIAGO',
        'SONA',
        'TEBARIO',
        'UNION DEL NORTE',
        'URRACA',
        'UTIRA',
        'VIGUI',
        'ZAPOTILLO',


    ],
    'PA-1' => [ //BOCAS DEL TORO
        'ALMIRANTE',
        'BAJO CEDRO',
        'BASTIMENTOS',
        'BOCAS DEL TORO',
        'CAUCHERO',
        'CHANGUINOLA',
        'CHIRIQUI',
        'CHIRIQUI GRANDE -BOCAS',
        'COCHIGRO',
        'EL EMPALME',
        'EL VALLE DE AGUA ARRIBA',
        'GUABITO',
        'ISLA  BOCAS',
        'LA GLORIA',
        'LAS DELICIAS',
        'LAS TABLAS',
        'MIRAMAR',
        'NANCE DE RISCO',
        'PUNTA LAUREL',
        'PUNTA PENA',
        'PUNTA ROBALO',
        'RAMBALA',
        'TERIBE',
        'TIERRA OSCURA',
        'VALLE DEL RISCO'
    ],
    'PA-10' => [
        'SAN CARLOS',
        'ARRAIJAN',

    ],
    'PA-6' => [ //herera
        'CABUYA',
        'CAPURI',
        'CERRO LARGO',
        'CHEPO',
        'CHITRE',
        'CHUMICAL',
        'CHUPAMPA',
        'CORONADO',
        'EL BARRERO',
        'EL CALABACITO',
        'EL CEDRO',
        'EL CIRUELO',
        'EL LIMON',
        'EL PAJARO',
        'EL PEDREGOSO',
        'EL RINCON',
        'EL TIJERA',
        'EL TORO',
        'LA ARENA',
        'LA PITALOZA',
        'LA VILLA DE LOS SANTOS',
        'LAS CABRAS',
        'LAS LLANAS',
        'LAS MINAS',
        'LEONES',
        'LLANO BONITO',
        'LLANO DE LA CRUZ',
        'LLANO GRANDE',
        'LOS CANELOS',
        'LOS CASTILLOS',
        'LOS CERRITOS',
        'LOS CERROS DE PAJA',
        'LOS LLANOS',
        'LOS POZOS',
        'MENCHACA',
        'MONAGRILLO',
        'OCU',
        'PARIS',
        'PARITA',
        'PENAS CHATAS',
        'PESE',
        'PORTOBELILLO',
        'POTUGA',
        'QUEBRADA DEL ROSARIO',
        'QUEBRADA EL CIPRIAN',
        'RINCON HONDO',
        'SABANA GRANDE',
        'SAN JUAN BAUTISTA',
        'SANTA MARIA',
    ],
    'PA-5' => //darien
    [
        'AGUA FRIA',
        'BOCA DE CUPE',
        'CAMOGANTI',
        'CHEPIGANA',
        'COMARCA KUNA',
        'CUCUNATI',
        'EL REAL DE SANTA MARIA',
        'GARACHINE',
        'JAQUE',
        'LA PALMA',
        'LA PALMA DARIEN',
        'METETI',
        'PAYA',
        'PINOGANA',
        'PUCURO',
        'PUERTO PINA',
        'RIO CONGO',
        'RIO CONGO ARRIBA',
        'RIO IGLESIAS',
        'SAMBU',
        'SANTA FE',
        'SETEGANTI',
        'TAIMATI',
        'TUCUTI',
        'WARGANDI',
        'YAPE',
        'YAVIZA',

    ],
    'PA-3' => [ //COLON
        'ACHIOTE',
        'BARRIO NORTE',
        'BARRIO SUR',
        'BUENA VISTA',
        'CACIQUE',
        'CATIVA',
        'CIRICITO',
        'COCLE DEL NORTE',
        'COLON',
        'CRISTOBAL',
        'CUANGO',
        'EL GUABO',
        'EL GUASIMO',
        'ESCOBAL',
        'GARROTE',
        'GOBEA',
        'ISLA GRANDE',
        'LA ENCANTADA',
        'LIMON',
        'MARIA CHIQUITA',
        'MIGUEL DE LA BORDA',
        'MIRAMAR',
        'NOMBRE DE DIOS',
        'NUEVA',
        'NUEVO CHAGRES',
        'PALENQUE',
        'PALMAS BELLAS',
        'PALMIRA',
        'PINA',
        'PLAYA CHIQUITA',
        'PORTOBELO',
        'PROVIDENCIA',
        'PUERTO PILON',
        'RIO INDIO',
        'SABANITAS',
        'SALAMANCA',
        'SALUD',
        'SAN JOSE DEL GENERAL',
        'SAN JUAN',
        'SANTA ISABEL',
        'SANTA ROSA',
        'VIENTO FRIO',

    ],
    'PA-7' => [ //los santos

        'AGUA BUENA',
        'ALTOS DE GUERRA',
        'BAHIA HONDA',
        'BAJO CORRAL',
        'BAJOS DE GUERA',
        'BAYANO',
        'CAMBUTAL',
        'CANAS GORDAS',
        'CHUPA',
        'COROZAL',
        'EL BEBEDERO',
        'EL CACAO',
        'EL CANAFISTULO',
        'EL CARATE',
        'EL CEDRO',
        'EL COCAL',
        'EL CORTEZO',
        'EL ESPIRAL',
        'EL GUASIMO',
        'EL HATO',
        'EL MACANO',
        'EL MANANTIAL',
        'EL MUNOZ',
        'EL PEDRAGOSO',
        'ESPINO AMARILLO',
        'FLORES',
        'GUANICO',
        'GUARARE',
        'GUARARE ARRIBA',
        'ISLA DE CANAS',
        'LA COLORADA',
        'LA ENEA',
        'LA ESPIGADILLA',
        'LA LAJA',
        'LA MESA',
        'LA MIEL',
        'LA PALMA',
        'LA PALMA LOS SANTOS',
        'LA PASERA',
        'LA TIZA',
        'LA TRONOSA',
        'LA VILLA DE LOS SANTOS',
        'LAJAMINA',
        'LAS CRUCES',
        'LAS GUABAS',
        'LAS PALMAS',
        'LAS PALMITAS',
        'LAS TABLAS',
        'LAS TABLAS ABAJO',
        'LAS TRANCAS',
        'LLANO ABAJO',
        'LLANO DE PIEDRA',
        'LLANO LARGO',
        'LOS ANGELES',
        'LOS ASIENTOS',
        'LOS OLIVOS',
        'MACARACAS',
        'MARIABE',
        'MOGOLLON',
        'NUARIO',
        'ORIA ARRIBA',
        'PALMIRA',
        'PARAISO',
        'PARITILLA',
        'PEDASI',
        'PENA BLANCA',
        'PERALES',
        'POCRI',
        'PURIO',
        'RIO HONDO',
        'SABANA GRANDE',
        'SAN JOSE',
        'SAN MIGUEL',
        'SANTA ANA',
        'SANTO DOMINGO',
        'SESTEADERO',
        'TONOSI',
        'TRES QUEBRADAS',
        'VALLE RICO',
        'VALLERRIQUITO',
        'VILLA LOURDES',

    ],
    'PA-EM' => [ //COMARCA EMBERA - mbera wounan
        'CIRILO GUAINORA',
        'JINGURUDO',
        'LAJAS BLANCAS',
        'MANUEL ORTEGA',
        'PUERTO INDIO',
        'RIO SABALO',
        'UNION CHOCOE',

    ],
    'PA-4' => [ //CHIRIQUI
        'ALANJE',
        'ALTO BOQUETE',
        'ASERRIO DE GARICHE',
        'BACO',
        'BAGALA',
        'BAJO BOQUETE',
        'BELLA VISTA',
        'BIJAGUAL',
        'BOCA CHICA',
        'BOCA DEL MONTE',
        'BOQUERON',
        'BOQUETE',
        'BRENON',
        'BUGABA',
        'CALDERA',
        'CANAS GORDAS',
        'CANTA GALLO',
        'CERRO PUNTA',
        'CERRO VIEJO',
        'CHIRIQUI',
        'COCHEA',
        'CORDILLERA',
        'CORONADO',
        'DAVID',
        'DIVALA',
        'DOLEGA',
        'DOMINICAL',
        'DOS RIOS',
        'EL BONGO',
        'EL CRISTO',
        'EL NANCITO',
        'EL PORVENIR',
        'EL PUERTO',
        'EL TEJAR',
        'GOMEZ',
        'GUABAL',
        'GUACA',
        'GUALACA',
        'GUARUMAL',
        'GUAYABAL',
        'HORCONCITOS',
        'HORNITO',
        'JARAMILLO',
        'JUAY',
        'JUSTO FIDEL PALACIOS',
        'LA CONCEPCION',
        'LA ESTRELLA',
        'LAJAS ADENTRO',
        'LAJAS DE TOLE',
        'LAS LAJAS',
        'LAS LAJAS SAN FELIX',
        'LAS LOMAS',
        'LIMONES',
        'LOS ALGARROBOS',
        'LOS ANASTACIOS',
        'LOS ANGELES',
        'LOS NARANJOS',
        'MONTE LIRIO',
        'NUEVO MEXICO',
        'PAJA DE SOMBRERO',
        'PALMIRA',
        'PALO GRANDE',
        'PARAISO',
        'PASO CANOAS FRONTERA',
        'PEDREGAL',
        'PLAZA CAISAN',
        'POTRERILLOS',
        'POTRERILLOS ABAJO',
        'POTRERO DE CANA',
        'PROGRESO',
        'PUERTO ARMUELLES',
        'PUERTO ARMUELLESABECER',
        'QUEBRADA DE PIEDRA',
        'QUEREVALO',
        'REMEDIOS',
        'RINCON',
        'RIO SERENO',
        'RODOLFO AGUILAR DELGADO',
        'ROVIRA',
        'SAN ANDRES',
        'SAN CARLOS',
        'SAN FELIX',
        'SAN JUAN',
        'SAN LORENZO',
        'SAN PABLO NUEVO',
        'SAN PABLO VIEJO',
        'SANTA CLARA',
        'SANTA CRUZ',
        'SANTA LUCIA',
        'SANTA MARTA',
        'SANTA ROSA',
        'SANTO DOMINGO',
        'SANTO TOMAS',
        'SORTOVA',
        'STRASBUSGO',
        'TIJERAS',
        'TINAJAS',
        'TOLE',
        'VELADERO',
        'VOLCAN'

    ],
    'PA-2' => [ //COCLE
        'AGUADULCE',
        'ANTON',
        'BARRIOS UNIDOS',
        'CABALLERO',
        'CABUYA',
        'CANAVERAL',
        'CAPELLANIA',
        'CHIGUIRI ARRIBA',
        'COCLE',
        'EL CANO',
        'EL CHIRU',
        'EL COCO',
        'EL COPE',
        'EL CRISTO',
        'EL HARINO',
        'EL PALMAR',
        'EL PICACHO',
        'EL POTRERO',
        'EL RETIRO',
        'EL ROBLE',
        'EL VALLE',
        'GUZMAN',
        'JUAN DIAZ',
        'LA PAVA',
        'LA PINTADA',
        'LAS HUACAS',
        'LAS LOMAS',
        'LLANO GRANDE',
        'NATA',
        'OLA',
        'PAJONAL',
        'PENONOME',
        'PIEDRAS GORDAS',
        'POCRI',
        'RIO GRANDE',
        'RIO HATO',
        'RIO INDIO',
        'SAN JUAN DE DIOS',
        'SANTA RITA',
        'TOABRE',
        'TOZA',
        'TULU'

    ],

    'PA-8' => [ //panama 

        '24 DE DICIEMBRE',
        'AMELIA DENIS DE ICAZA',
        'ANCON',
        'ARNULFO ARIAS',
        'ARRAIJAN',
        'BELISARIO FRIAS',
        'BELISARIO PORRAS',
        'BELLA VISTA',
        'BETHANIA',
        'BRUJAS',
        'CANITA',
        'CERRO AZUL',
        'CHEPILLO',
        'CHEPO',
        'CHILIBRE',
        'CHIMAN',
        'CIUDAD DE PANAMA',
        'CIUDAD DE PANAMA OESTE',
        'CIUDAD PANAMA',
        'COMARCA KUNA DE MADUGANDI',
        'CORONADO',
        'CURUNDU',
        'EL CHORRILLO',
        'EL LLANO',
        'ERNESTO CORDOBA CAMPOS',
        'GONZALO VASQUEZ',
        'HERRERA DE CHORRERA',
        'JOSE DOMINGO ESPINAR',
        'JUAN DIAZ',
        'LA CHORRERA',
        'LA ENSENADA',
        'LA ESMERALDA',
        'LA EXPOSICION O CALIDONIA',
        'LA GUINEA',
        'LAS CUMBRES',
        'LAS LAJAS CHAME',
        'LAS MANANITAS',
        'LAS MARGARITAS',
        'LIDICE',
        'MATEO ITURRALDE',
        'OMAR TORRIJOS',
        'OTOQUE OCCIDENTE',
        'OTOQUE ORIENTE',
        'PACORA',
        'PARQUE LEFEVRE',
        'PASIGA',
        'PEDREGAL',
        'PEDRO GONZALEZ',
        'PUEBLO NUEVO',
        'RIO ABAJO',
        'RUFINA ALFARO',
        'SABOGA',
        'SAN FELIPE',
        'SAN FRANCISCO',
        'SAN MARTIN',
        'SAN MIGUEL',
        'SAN MIGUELITO',
        'SANTA ANA',
        'SANTA CRUZ DE CHININA',
        'SANTA RITA',
        'TABOGA',
        'TOCUMEN',
        'TORTI',
        'UNION SANTENA',
        'VICTORIANO LORENZO',
    ],
    'PA-10'=> [
        'SAN CARLOS',
        'ARRAIJAN',
        'BURUNGA',
        'CERRO SILVESTRE',
        'JUAN DEMOSTENES AROSEMENA',
        'NUEVO EMPERADOR',
        'SANTA CLARA',
        'VERACRUZ',
        'VISTA ALEGRE',
        'CAPIRA',
        'CAIMITO',
        'CAMPANA',
        'CERMENO',
        'CIRI DE LOS SOTOS',
        'CIRI GRANDE',
        'EL CACAO',
        'LA TRINIDAD',
        'LAS OLLAS ARRIBA',
        'VILLA CARMEN',
        'VILLA ROSARIO',
        'SANTA ROSA',
        'CHAME',
        'BEJUCO',
        'BUENOS AIRES',
        'CABUYA',
        'CHICA',
        'EL LIBANO',
        'LAS LAJAS',
        'NUEVA GORGONA',
        'PUNTA CHAME',
        'SAJALICES',
        'SORA',
        'BARRIO BALBOA',
        'BARRIO COLON',
        'AMADOR',
        'AROSEMENA',
        'EL ARADO',
        'EL COCO',
        'FEUILLET',
        'GUADALUPE',
        'HERRERA',
        'HURTADO',
        'ITURRALDE',
        'LA REPRESA',
        'LOS DIAZ',
        'MENDOZA',
        'OBALDIA',
        'PLAYA LEONA',
        'PUERTO CAIMITO',
        'SANTA RITA',
        'SAN CARLOS',
        'EL ESPINO',
        'EL HIGO',
        'GUAYABITO',
        'LA ERMITA',
        'LA LAGUNA',
        'LAS UVAS',
        'LOS LLANITOS',
        'SAN JOSE',

    ]


];
